"""HTML report output with embedded CSS."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from container_audit.scanner import ScanResult, Severity, Status


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Container Audit Report - {target}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0d1117; color: #c9d1d9; padding: 2rem; }}
  .container {{ max-width: 960px; margin: 0 auto; }}
  h1 {{ color: #58a6ff; margin-bottom: 0.5rem; }}
  .meta {{ color: #8b949e; margin-bottom: 2rem; }}
  .score-box {{ display: inline-block; padding: 1rem 2rem; border-radius: 8px; font-size: 2rem; font-weight: bold; margin: 1rem 0; }}
  .score-good {{ background: #0d4429; color: #3fb950; }}
  .score-mid {{ background: #3d2e00; color: #d29922; }}
  .score-bad {{ background: #490202; color: #f85149; }}
  .summary {{ display: grid; grid-template-columns: repeat(5, 1fr); gap: 1rem; margin: 2rem 0; }}
  .stat {{ padding: 1rem; border-radius: 8px; text-align: center; background: #161b22; border: 1px solid #30363d; }}
  .stat .num {{ font-size: 1.5rem; font-weight: bold; }}
  .stat .label {{ font-size: 0.8rem; color: #8b949e; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
  th, td {{ padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid #21262d; }}
  th {{ background: #161b22; color: #58a6ff; font-weight: 600; }}
  tr:hover {{ background: #161b22; }}
  .sev-critical {{ color: #f85149; font-weight: bold; }}
  .sev-high {{ color: #f85149; }}
  .sev-medium {{ color: #d29922; }}
  .sev-low {{ color: #58a6ff; }}
  .sev-info {{ color: #8b949e; }}
  .status-pass {{ color: #3fb950; }}
  .status-fail {{ color: #f85149; }}
  .status-warn {{ color: #d29922; }}
  .remediation {{ color: #8b949e; font-size: 0.85rem; font-style: italic; }}
  .footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #21262d; color: #8b949e; font-size: 0.8rem; }}
</style>
</head>
<body>
<div class="container">
  <h1>🔒 Container Audit Report</h1>
  <div class="meta">
    <p>Target: <strong>{target}</strong> | Scan Type: <strong>{scan_type}</strong> | Generated: <strong>{timestamp}</strong></p>
  </div>

  <div class="score-box {score_class}">Security Score: {score}/100</div>

  <div class="summary">
    <div class="stat"><div class="num" style="color:#f85149">{critical}</div><div class="label">Critical</div></div>
    <div class="stat"><div class="num" style="color:#f85149">{high}</div><div class="label">High</div></div>
    <div class="stat"><div class="num" style="color:#d29922">{medium}</div><div class="label">Medium</div></div>
    <div class="stat"><div class="num" style="color:#58a6ff">{low}</div><div class="label">Low</div></div>
    <div class="stat"><div class="num" style="color:#3fb950">{passed}</div><div class="label">Passed</div></div>
  </div>

  <table>
    <thead>
      <tr><th>Status</th><th>Severity</th><th>Check</th><th>Description</th><th>Remediation</th></tr>
    </thead>
    <tbody>
      {rows}
    </tbody>
  </table>

  <div class="footer">
    Generated by <a href="https://github.com/HYMichellexdd/container-audit" style="color:#58a6ff">container-audit</a> v0.1.0
  </div>
</div>
</body>
</html>"""


class HtmlReporter:
    """Generate HTML security report."""

    def report(self, result: ScanResult) -> str:
        """Return HTML string of scan results."""
        score = result.score
        score_class = "score-good" if score >= 80 else "score-mid" if score >= 50 else "score-bad"

        rows = []
        for f in result.findings:
            sev_class = f"sev-{f.severity.value}"
            status_class = f"status-{f.status.value}"
            status_text = f.status.value.upper()
            rows.append(
                f'<tr><td class="{status_class}">{status_text}</td>'
                f'<td class="{sev_class}">{f.severity.value.upper()}</td>'
                f'<td><strong>{f.check_id}</strong><br>{f.title}</td>'
                f'<td>{f.description}</td>'
                f'<td class="remediation">{f.remediation}</td></tr>'
            )

        return HTML_TEMPLATE.format(
            target=result.target,
            scan_type=result.scan_type,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            score=score,
            score_class=score_class,
            critical=result.critical_count,
            high=result.high_count,
            medium=result.medium_count,
            low=result.low_count,
            passed=result.total_passed,
            rows="\n".join(rows),
        )

    def save(self, result: ScanResult, output_path: str) -> Path:
        """Save HTML report to file."""
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.report(result))
        return path
